fix: unused function errors
bs_sheepdog.c:297:19: error: unused function 'is_data_obj_writeable' [-Werror,-Wunused-function]
static inline int is_data_obj_writeable(struct sheepdog_inode *inode,
                  ^
bs_sheepdog.c:303:19: error: unused function 'is_data_obj' [-Werror,-Wunused-function]
static inline int is_data_obj(uint64_t oid)
                  ^
bs_sheepdog.c:308:24: error: unused function 'data_oid_to_idx' [-Werror,-Wunused-function]
static inline uint64_t data_oid_to_idx(uint64_t oid)
                       ^
bs_sheepdog.c:318:24: error: unused function 'vid_to_vmstate_oid' [-Werror,-Wunused-function]
static inline uint64_t vid_to_vmstate_oid(uint32_t vid, uint32_t idx)

Signed-off-by: FUJITA Tomonori <fujita.tomonori@gmail.com>